### ISSUE TITLE
Issue with starting the App.vue!

### ISSUE THREAD

**Issue by GilloDaby** [octoman90/BDO-Leaderboards#26]
I was using your old code for the guild stats. I was hoping to update my file to get the new code etc. But now this won't work anymore. I think I'm not able to initialize to App.vue and cause of this my page is white.

Sorry for my english I try my best! Thanks for the help

**Comment by octoman90** [comment]
Create a file named `.env` in the main directory (the same directory where `package.json` is) with these contents:
```bash
VUE_APP_API_BASE=http://127.0.0.1:8001
VUE_APP_USE_HASH_HISTORY=false
```

The address in the first line should point to the address to which your [BDO-REST-API](https://github.com/octoman90/BDO-REST-API) instance listens to.The one above is default if it's self-hosted; you can also use `VUE_APP_API_BASE=https://boiling-mountain-53521.herokuapp.com` but it might be slow or even stop working sometimes.

The second line is there to fix a very specific behaviour of some hosting services and should be set to false in most cases.

After creating the file, run `yarn install` and `yarn start` (or `npm install` and `npm run start`) and it should work.

I'm going to make this process easier and describe it in the repo readme soon.

**Comment by GilloDaby** [comment]
Thanks a lot! I will try soon
